export * from './antecedent'
export * from './array-concat-identity'
export * from './number-additive-identity'
export * from './number-multiplicative-identity'
export * from './object-intersection-identity'
export * from './string-concat-identity'
