export * from './is-decimal'
export * from './is-natural'
export * from './is-negative'
export * from './is-non-negative'
export * from './is-non-positive'
export * from './is-positive'
export * from './is-whole'
export * from './is-zero'
