export * from './is-array-identity'
export * from './is-number-additive-identity'
export * from './is-number-multiplicative-identity'
export * from './is-object-identity'
export * from './is-string-identity'
